import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { trpc } from "../../utils/trpc";

const Spaces: NextPage = () => {
  const memberships = trpc.memberships.getAll.useQuery();
  const create = trpc.spaces.create.useMutation();

  const onClickCreateSpace = () => {
    create.mutate({
      name: "Hello new space",
    });
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>Spaces</div>
        <button onClick={onClickCreateSpace}>Create Space</button>
        <div>
          <ul>
            {memberships.data?.map((mem) => (
              <li>
                <Link href={`/${mem.organization.slug}/spaces`}>
                  {mem.organization.name}
                </Link>
              </li>
            ))}
          </ul>
        </div>
      </main>
    </>
  );
};

export default Spaces;
