import { type NextPage } from "next";
import { useRouter } from "next/router";
import Head from "next/head";
import Link from "next/link";

import { api } from "api";

const Spaces: NextPage = () => {
  const router = useRouter();
  const spaces = api.spaces.getAll.useQuery();
  const create = api.spaces.create.useMutation();

  const onClickCreateSpace = () => {
    create.mutate({
      name: "Hello new space",
    });
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>Spaces</div>
        <button onClick={onClickCreateSpace}>Create Space</button>
        <div>
          <ul>
            {spaces.data?.map((space) => (
              <li key={space.id}>
                <Link
                  href={{
                    pathname: `spaces/${space.slug}`,
                    query: router.query,
                  }}
                >
                  {space.name}
                </Link>
              </li>
            ))}
          </ul>
        </div>
      </main>
    </>
  );
};

export default Spaces;
